leftnav:
- identifier: a56ae837-1ddc-01d2-7c9d-93e3b29b5265
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 2aec50f5-04d3-4372-5e86-10622a4ce095
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 878e945c-53f1-4f06-f7ed-408d51318896
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 2f390d9c-561f-cf20-808e-8cbcc4d7478b
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: a67f5ffc-0769-f081-22c9-02fcce6bb66e
  name: Projects
  pageRef: /pages/projects
  weight: 50
